package br.com.ungaratto93.tasks.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

public class TaskPrimaryKey {

    @DynamoDBHashKey(attributeName = "TaskID")
    @DynamoDBAutoGeneratedKey
    private String taskID;

    @DynamoDBRangeKey(attributeName = "Priority")
    private String priority;

    public TaskPrimaryKey() {
    }

    public TaskPrimaryKey(String id) {
        this.taskID = id;
    }

    public TaskPrimaryKey(String id, String priority) {
        this.taskID = id;
        this.priority = priority;
    }

    public void setId(String id) {
        this.taskID = id;
    }

    public String getId() {
        return this.taskID;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getPriority() {
        return this.priority;
    }
}
