package br.com.ungaratto93.tasks.api.entities;

import br.com.ungaratto93.tasks.api.utils.LocalDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

@DynamoDBTable(tableName = "tasks")
public class Task implements Serializable {

    private static final long serialVersionUID = -4282005207341771716L;


    @Id
    private TaskPrimaryKey pk;

    @JsonProperty("task_name")
    private String taskName;

    @JsonProperty("task_description")
    private String taskDescription;


    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp(pattern="dd-MM-yyyy'T'HH:mm:ss.SSS'Z'", timeZone="America/Sao_Paulo")
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp(pattern="dd-MM-yyyy'T'HH:mm:ss.SSS'Z'", timeZone="America/Sao_Paulo")
    private Date updatedAt;

    @JsonProperty("task_done")
    private Boolean taskDone;

    public Task() {
    }

    public Task(TaskPrimaryKey pk, String taskName, String taskDescription, LocalDateTime createdAt, LocalDateTime updatedAt, Boolean taskDone) {
        this.pk = pk != null ? pk : new TaskPrimaryKey();
        this.taskName = taskName;
        this.taskDescription = taskDescription;
        this.taskDone = taskDone;
    }

    public Task(TaskPrimaryKey primaryKey, String priority, String taskName, String taskDescription, LocalDateTime updatedAt, Boolean taskDone) {
        this.pk = primaryKey;
        this.pk.setPriority(priority);
        this.taskName = taskName;
        this.taskDescription = taskDescription;
        this.taskDone = taskDone;
    }

    @DynamoDBHashKey(attributeName = "TaskID")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.pk.getId();
    }

    public void setId(String id) {
        if (pk == null)
            pk = new TaskPrimaryKey(id);

        pk.setId(id);
        //this.pk = new TaskPrimaryKey(id);
    }
    @DynamoDBRangeKey(attributeName = "Priority")
    public String getPriority() {
        return this.pk.getPriority();
    }

    public void setPriority(String priority) {
        this.pk = pk != null ? pk : new TaskPrimaryKey();
        this.pk.setPriority(priority);
    }
    @DynamoDBAttribute(attributeName = "task_name")
    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    @DynamoDBAttribute(attributeName = "task_description")
    public String getTaskDescription() {
        return taskDescription;
    }

    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }
    @DynamoDBAttribute(attributeName = "created_at")
    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @DynamoDBAttribute(attributeName = "updated_at")
    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @DynamoDBAttribute(attributeName = "task_done")
    public Boolean getTaskDone() {
        return taskDone;
    }

    public void setTaskDone(Boolean taskDone) {
        this.taskDone = taskDone;
    }
}
